### ISSUE TITLE
Applications using fullscreen with a smaller geometry than the output geometry are misplaced

### ISSUE THREAD

**Issue by Consolatis** [labwc/labwc#2779]
We should center the window in those cases and put a solid background behind everything. That is also what the spec requires.

>> Just a slightly related note: The reason the smaller surface is shown on the top-left and the other windows being visible is due to labwc being [non-spec compliant](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/stable/xdg-shell/xdg-shell.xml?ref_type=heads#L1078): the surface should be centered on the fullscreen output in case the dimensions are smaller than the full output geometry. We should also add a solid background behind it, covering the full output. Technically we are also supposed to put a solid background behind any fullscreen surface if the surface is not completely opaque (which I am absolutely not a fan of). Ref: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/116
> 
> This explains the strange behavior that happens with labwc and winewayland.drv.
> 
> This is what a game through wine wayland in labwc currently looks like:
> ![Image](https://gitlab.winehq.org/-/project/5/uploads/60010f1bf0218f93e5455081d04c3840/screenshot_05-03-25_02-03-51.png)
> 
> ...and this is what it's supposed to look like (wine xwayland in labwc):
> ![Image](https://gitlab.winehq.org/-/project/5/uploads/48d2fee421f47205d6d2565686f8fc59/screenshot_05-03-25_02-02-46.png)
> 
> Basically, it's impossible to play old games using wine wayland on labwc. 

 _Originally posted by @danielfrrrr in [#2774](https://github.com/labwc/labwc/issues/2774#issuecomment-2927870760)_

**Comment by qrp73** [comment]
I'm not sure that centering will help much. And it happens for native Linux games using SDL2 library either. When you run the game running with 640x480 resolution with default SDL x11 driver you will get this:

<img width="1280" height="1024" alt="Image" src="https://github.com/user-attachments/assets/ab8697a1-97f8-42a1-99af-09c0b1462b64" />



But if you run it with ```SDL_VIDEODRIVER=wayland quake3``` it works as expected:

<img width="1280" height="1024" alt="Image" src="https://github.com/user-attachments/assets/30edac2f-5348-4667-8e0e-a470f347c11c" />

So, it seems like some issue with display mode set or scaling for x11 driver.


Note that in both cases the game running in fullscreen mode, so it seems that it should use native 640x480 display resolution, but for some reason there is some issue with x11 driver and it is unusable. 

With wayland driver it works great. The only issue that I found, is that sometimes (very-very rare) there is broken mouse support at game startup (it doesn't respond on mouse movement at all), so you need to close it and restart again.

**Comment by danielfikko** [comment]
I think that will help. Apparently Wine can even fix this behavior on their end, but instead Wine expects the compositor to do it: https://bugs.winehq.org/show_bug.cgi?id=57456#c1. So I don't think Wine will do anything. But I see your issue, ideally windows should be scaled and filled to the resolution of your monitor, I face the same issue with `winewayland.drv`: https://bugs.winehq.org/show_bug.cgi?id=57925. In contrast, with `winex11.drv` there is no such issue, so I'm not sure if this is a compositor job.

**Comment by danielfikko** [comment]
Hi, @Consolatis. In my last message, I said I wasn't sure if this was the compositor's job, but I've been testing Weston and it seems that Weston fills the window to your monitor's resolution, instead of centering the window and putting a black background. I think this is better, as there are no black bars on the sides. Do you think it's possible to implement this in labwc?

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/78ed50d6-116d-4ed3-8967-6601eb9c3f13" />

**Comment by Consolatis** [comment]
> Hi, [@Consolatis](https://github.com/Consolatis). In my last message, I said I wasn't sure if this was the compositor's job, but I've been testing Weston and it seems that Weston fills the window to your monitor's resolution, instead of centering the window and putting a black background. I think this is better, as there are no black bars on the sides. Do you think it's possible to implement this in labwc?


That would not be [spec compliant](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/stable/xdg-shell/xdg-shell.xml?ref_type=heads#L1081) :
> 	If the surface doesn't cover the whole output, the compositor will
	position the surface in the center of the output and compensate with
	with border fill covering the rest of the output. The content of the
	border fill is undefined, but should be assumed to be in some way that
	attempts to blend into the surrounding area (e.g. solid black).

**Comment by danielfikko** [comment]
Couldn't it be implemented as an optional configuration? Sorry to be so insistent, but I've completely lost hope that Wine will fix these two issues, so my only chance is to wait for it to be fixed in labwc.

**Comment by Consolatis** [comment]
> Couldn't it be implemented as an optional configuration?

Hm.. I guess technically we'd only need to call `wlr_scene_buffer_set_dest_size()` on fullscreen / unfullscreen based on some window rule property. If the application then uses the correct geometry it wouldn't change anything and if it would use a smaller geometry wlroots would automatically scale it up. Didn't test this approach though. Thoughts @tokyo4j ?

**Comment by jp7677** [comment]
Isn’t that a use case for https://github.com/ValveSoftware/gamescope ?

**Comment by danielfikko** [comment]
Yes. I just tested Wine with gamescope and the game window is scaled!

**Comment by tokyo4j** [comment]
> I've been testing Weston and it seems that Weston fills the window to your monitor's resolution, instead of centering the window and putting a black background.

I think this is not true. Weston centers the fullscreen window and fills the background with black:

<img width="1042" height="678" alt="Image" src="https://github.com/user-attachments/assets/d8c4e505-7d74-4ea9-8d91-41fddfed9722" />

Test app: https://github.com/tokyo4j/wayland-demo/tree/small-fullscreen-window

So I wonder why SWAT4 window is scaled in weston... I guess there's some difference in how wlroots/weston negotiates with xwayland windows about their geometry?

> Hm.. I guess technically we'd only need to call `wlr_scene_buffer_set_dest_size()` on fullscreen / unfullscreen based on some window rule property. If the application then uses the correct geometry it wouldn't change anything and if it would use a smaller geometry wlroots would automatically scale it up. Didn't test this approach though. Thoughts @tokyo4j ?

It sounds like a dirty hack to me. `wlr_scene_buffer_set_dest_size()` is called by `wlr_scene.c` in wlroots and calling that function also from labwc is racy and I'm afraid it breaks some assumption in wlroots code. It will also be more complicated when the fullscreen window creates subsurfaces or popups.

So we can do:
- Investigate why SWAT4 window is scaled in weston, and implement the same logic in wlroots/labwc if possible
- Make labwc follow the wayland spec by centering fullscreen windows and filling the background with black

**Comment by danielfikko** [comment]
> I think this is not true. Weston centers the fullscreen window and fills the background with black:

Thanks for correcting me, especially since I've been mentioning Weston's behavior in the issue tracker of other compositors that don't follow the specification either!!

> So I wonder why SWAT4 window is scaled in weston... I guess there's some difference in how wlroots/weston negotiates with xwayland windows about their geometry?

~I'm not a programmer, so I don't know the technical terms. But looking at the screenshot of your test client, the window geometry couldn't be scaled to the output resolution without stretching the window. So I think Weston only scales windows that are scalable without stretching~. EDIT: Well, I think I spoke nonsense. Because looking at the SWAT 4 window, it also seems that it is not possible to scale the window without stretching, but in fact it is.

~I think Weston uses the `viewporter` protocol for this~. EDIT: Sorry, I'd better be quiet and leave the assumptions to you. I'll attach the log of SWAT 4 running through Weston, in case it's useful:
[swat4-weston-log.txt](https://github.com/user-attachments/files/21808231/swat4-weston-log.txt)

By the way, this issue only occurs with `winewayland.drv`. There is no issue with `winex11.drv` (xwayland), but apparently SDL2 games running through xwayland also suffer from this issue.

**Comment by danielfikko** [comment]
To be fair, of all the compositors I tested, Weston is the only one that scales the window, the other compositors either just center it and put a black background or do not follow the specification. Also, it may not be necessary for labwc to scale the windows:

There are three MRs that implement display mode change (which is basically window scaling) for `winewayland.drv`: [1](https://gitlab.winehq.org/wine/wine/-/merge_requests/4947), [2](https://gitlab.winehq.org/wine/wine/-/merge_requests/5057), and [3](https://gitlab.winehq.org/wine/wine/-/merge_requests/5680). All were closed in favor of this MR: https://gitlab.winehq.org/wine/wine/-/merge_requests/6804. And this comment from the main developer of `winewayland.drv` suggests that window scaling was implemented by this MR:

<img width="940" height="90" alt="Image" src="https://github.com/user-attachments/assets/6c6fa39a-dd67-4525-bd52-0f74ee7676f8" />

But when tested against labwc, it doesn't work, unlike the other three MRs, which I tested and the window is scaled. Could it be the fault of labwc that this MR doesn't work? If so, it will only be necessary to fix whatever the issue is and that's it: `winewayland.drv` will scale the window without requiring labwc to add an option for that. And if not, I can live with the black borders.

Anyway, my whole comment is just to clarify that you don't need to implement this window scaling feature, only if you think it will be useful.

**Comment by johanmalm** [comment]
@danielfrrrr Thoughts on #3228 ?

**Comment by danielfikko** [comment]
> [@danielfrrrr](https://github.com/danielfrrrr) Thoughts on [#3228](https://github.com/labwc/labwc/pull/3228) ?

First of all, thank you very much for working on this feature! :)

I tested four old games and your PR worked perfectly, according to its purpose: All games were centered. Just a few observations...

I tested `ToggleFullscreen`/`ToggleMaximize` on these games (through Wine) and a strange behavior occurs: The games start in full screen, when you run `ToggleFullscreen` and then `ToggleMaximize`, the game window moves to the right. After that, when you run `ToggleFullscreen` twice, the game window is scaled, filling your entire output. This is not the fault of this PR, it happens even without this PR (it's probably the fault of `winewayland.drv`). Anyway, I'm just mentioning this because you might want my feedback on `ToggleFullscreen`/`ToggleMaximize`, but given the immaturity of `winewayland.drv`, it's a little tricky to say how this PR is acting with this strange behavior of `winewayland.drv`.

And I ran some tests changing the resolution of the game window at runtime, and with the exception of one issue, your PR worked fine! As for the issue, the game Splinter Cell 3: Chaos Theory starts at a lower resolution than my output, so the window is centered. However, the game supports the same resolution as my output (1920x1080) and when I set that resolution, the game window moves to the right of my output. There is a workaround, which is to simply run `ToggleFullscreen` once and the window will be positioned correctly. Perhaps it is the same issue mentioned above with `winewayland.drv` (?). I will attach the labwc output log reproducing this issue (you can search for `ToggleFullscreen`, the issue was reproduced a few seconds before I applied the workaround):
[labwc-output-log.txt](https://github.com/user-attachments/files/23736662/labwc-output-log.txt)

Honestly, I believe that these two issues are both the fault of `winewayland.drv` and that your PR is functioning very well. Once again, thank you very much!

**Comment by johanmalm** [comment]
@danielfrrrr Thanks for testing. Considering that we're dealing with the commit-handler here, anything we do is quite expensive so we don't want to too many `if (this)` and `if (that)`. In other words, it feels better to me to ignore surface size changes after fullscreen has been initially established.

**Comment by danielfikko** [comment]
As for the black background, sway can be used as a reference:
https://github.com/swaywm/sway/blob/897e7688bb415c40f8bc104bd526ddba537255f1/include/sway/output.h#L34-L39

https://github.com/search?q=repo%3Aswaywm%2Fsway%20fullscreen_background&type=code

wlroots documentation:
https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/abf80b529e48823e21215a6ccc4653e2c2a4a565/include/wlr/types/wlr_scene.h#L145-150

https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/abf80b529e48823e21215a6ccc4653e2c2a4a565/include/wlr/types/wlr_scene.h#L452-458

Again, I'm not a programmer, I only know a few things about shell scripting (so I know some C concepts, such as functions). That said, I'll try to implement the black background on my own (and without AI!). I probably won't succeed, but the references are here, in case someone who knows C can implement it.

I understand that Consolatis has shown that he is not a big fan of this approach, but at least I will be able to use it in a local fork.

**Comment by Consolatis** [comment]
> I understand that Consolatis has shown that he is not a big fan of this approach, but at least I will be able to use it in a local fork.

I am absolutely fine with having a black background behind fullscreen windows which are smaller than the output geometry. This is useful for example for video players because they can just keep their aspect ratio and let the compositor handle the rest.

What I am really not a big fan of is always having a black background behind fullscreen window because that would break fullscreen transparency for things like terminals.

**Comment by danielfikko** [comment]
> I am absolutely fine with having a black background behind fullscreen windows which are smaller than the output geometry. This is useful for example for video players because they can just keep their aspect ratio and let the compositor handle the rest.
> 
> What I am really not a big fan of is always having a black background behind fullscreen window because that would break fullscreen transparency for things like terminals.

I see. That's good to know. I thought the black background wouldn't be accepted at all. :O

Well, in the last few hours I tried to implement it, and obviously someone who knows absolutely nothing about C wouldn't be able to. I basically copied and pasted the [sway code](https://github.com/search?q=repo%3Aswaywm%2Fsway%20fullscreen_background&type=code) and replaced it with labwc equivalents:

```diff
diff --git a/include/view.h b/include/view.h
index 2d894265..8216ecc3 100644
--- a/include/view.h
+++ b/include/view.h
@@ -135,6 +135,7 @@ struct view {
        enum view_type type;
        const struct view_impl *impl;
        struct wl_list link;
+       struct wlr_scene_rect *fullscreen_background;

        /*
         * The primary output that the view is displayed on. Specifically:
diff --git a/src/view.c b/src/view.c
index f0472289..61e3818b 100644
--- a/src/view.c
+++ b/src/view.c
@@ -1756,6 +1756,7 @@ view_set_fullscreen(struct view *view, bool fullscreen)
        }

        set_fullscreen(view, fullscreen);
+       view->fullscreen_background = wlr_scene_rect_create(view->scene_tree, 0, 0, (float[4]){0.f, 0.f, 0.f, 1.f});
        if (view_is_floating(view)) {
                view_apply_natural_geometry(view);
        } else {
```

It didn't work... does that make any sense? And feel free to laugh.

**Comment by Consolatis** [comment]
> It didn't work... does that make any sense?

The basic idea is fine. The issue is that you are using `0` for the width and height arguments and thus it won't show.
Another issue is that it would be rendered on top of the window so you'd only see the black rect.
<details><summary>Something like this should make it work, completely untested</summary>

```diff
diff --git a/include/view.h b/include/view.h
index 2d894265..3ae51e39 100644
--- a/include/view.h
+++ b/include/view.h
@@ -166,6 +166,7 @@ struct view {
 	struct wlr_surface *surface;
 	struct wlr_scene_tree *scene_tree;
 	struct wlr_scene_tree *content_tree;
+	struct wlr_scene_rect *fullscreen_background;
 
 	/* These are never NULL and an empty string is set instead. */
 	char *title;
diff --git a/src/view.c b/src/view.c
index f0472289..e461f1d7 100644
--- a/src/view.c
+++ b/src/view.c
@@ -1753,6 +1753,18 @@ view_set_fullscreen(struct view *view, bool fullscreen)
 		interactive_cancel(view);
 		view_store_natural_geometry(view);
 		view_invalidate_last_layout_geometry(view);
+
+		if (!view->fullscreen_background) {
+			const float black[4] = { 0, 0, 0, 1 };
+			view->fullscreen_background = wlr_scene_rect_create(
+				view->scene_tree, 0, 0, black);
+			wlr_scene_node_lower_to_bottom(&view->fullscreen_background->node);
+		}
+		wlr_scene_rect_set_size(view->fullscreen_background,
+			view->output->wlr_output->width, view->output->wlr_output->height);
+	}
+	if (view->fullscreen_background) {
+		wlr_scene_node_set_enabled(&view->fullscreen_background->node, fullscreen);
 	}
 
 	set_fullscreen(view, fullscreen);
```

</details>

**Comment by danielfikko** [comment]
While I came close, I was still quite far off. Thanks for the corrections.

And your patch worked:

|||
|:-:|:-:|
|<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/6cfb9674-bf46-47ce-b387-c29e30c6a190" />|<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/83ec56c2-12c9-4378-b74d-392eed199b8f" />|

Thank you! I will use it locally. 😄

**Comment by Consolatis** [comment]
<details><summary>This might also center it, again completely untested:</summary>

```diff
diff --git a/include/view.h b/include/view.h
index 2d894265..3ae51e39 100644
--- a/include/view.h
+++ b/include/view.h
@@ -166,6 +166,7 @@ struct view {
 	struct wlr_surface *surface;
 	struct wlr_scene_tree *scene_tree;
 	struct wlr_scene_tree *content_tree;
+	struct wlr_scene_rect *fullscreen_background;
 
 	/* These are never NULL and an empty string is set instead. */
 	char *title;
diff --git a/src/view.c b/src/view.c
index f0472289..366c653e 100644
--- a/src/view.c
+++ b/src/view.c
@@ -606,6 +606,15 @@ view_moved(struct view *view)
 	assert(view);
 	wlr_scene_node_set_position(&view->scene_tree->node,
 		view->current.x, view->current.y);
+
+	if (view->fullscreen) {
+		wlr_scene_node_set_position(&view->content_tree->node,
+			(view->output->wlr_output->width - view->current.width) / 2,
+			(view->output->wlr_output->height - view->current.height) / 2);
+	} else {
+		wlr_scene_node_set_position(&view->content_tree->node, 0, 0);
+	}
+
 	/*
 	 * Only floating views change output when moved. Non-floating
 	 * views (maximized/tiled/fullscreen) are tied to a particular
@@ -1753,6 +1762,18 @@ view_set_fullscreen(struct view *view, bool fullscreen)
 		interactive_cancel(view);
 		view_store_natural_geometry(view);
 		view_invalidate_last_layout_geometry(view);
+
+		if (!view->fullscreen_background) {
+			const float black[4] = { 0, 0, 0, 1 };
+			view->fullscreen_background = wlr_scene_rect_create(
+				view->scene_tree, 0, 0, black);
+			wlr_scene_node_lower_to_bottom(&view->fullscreen_background->node);
+		}
+		wlr_scene_rect_set_size(view->fullscreen_background,
+			view->output->wlr_output->width, view->output->wlr_output->height);
+	}
+	if (view->fullscreen_background) {
+		wlr_scene_node_set_enabled(&view->fullscreen_background->node, fullscreen);
 	}
 
 	set_fullscreen(view, fullscreen);
```

</details>

**Comment by jlindgren90** [comment]
In #3233, I've combined the `wlr_scene_rect` idea with the centering logic I proposed previously. It works for me with a simple test client.

@danielfrrrr can you test please?

**Comment by danielfikko** [comment]
@jlindgren90 Thank you very much to you and everyone who is contributing for working on this. I found some issues, which I will comment on below, but I wanted to say that I am very grateful for your work on this: the games look great centered and with the black background. 😃 

I tested your PR with `weston-simple-egl -f -r` and it worked as expected: the window is centered and there is a black background.

Regarding games through Wine using `winewayland.drv`: games start centered, but without a black background. For the black background to appear, you need to run `ToggleFullscreen` twice or press `Alt + Tab` out of the game and back in.

And the situation is slightly worse in Splinter Cell 1 (2002), Splinter Cell 2: Pandora Tomorrow and Splinter Cell 3: Chaos Theory...

The three games start with an introductory video, just like SWAT 4, and without the black background. Applying the workaround mentioned above, of pressing `ToggleFullscreen` or `Alt + Tab`, does not work during the videos. You can only apply the workaround during the start menu or in-game.

Applying this workaround appears to be permanent, so subsequent videos will have a black background. However, if you happen to press `ToggleFullscreen` once during any video, the game window will be decentralized, moving to the left of the output and the black background will disappear. The workaround will no longer work, only during a menu or in-game.

You can get an idea from this video:

https://github.com/user-attachments/assets/0026c984-0f82-4cea-b82b-9354f4ccc5a6

**Comment by jlindgren90** [comment]
@danielfrrrr thanks for the detailed report and video. There was a race condition if the client was slow to respond to a configure request, which prevented the background fill from being enabled (even though the view was centered). I was able to reproduce it with Wine/Wayland and an old (pre-remaster) version of StarCraft. Assuming it's the same problem you saw, it should be fixed now (in #3233).

**Comment by danielfikko** [comment]
@jlindgren90 Yes, now the games start with a black background, except for Splinter Cell 3: Chaos Theory: the game starts with an introductory video. Also, the first three games in the Splinter Cell franchise still have the same issue: if you press `ToggleFullscreen` once during any video, the black background disappears and the game window is moved to the left of the output.

In addition, when you actually enter the game in Splinter Cell 3: Chaos Theory, the black background also disappears:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2d046126-a286-4cab-9dc9-6ff911e8087f" />

Looking through the articles for these games on PCGamingWiki, all three games appear to use Bink Video for video cutscenes. You can find some games that use Bink Video here:
https://www.pcgamingwiki.com/wiki/Bink_Video

Even so, it may be a specific issue with the Splinter Cell franchise. So, please send me your Steam so I can happily purchase Splinter Cell 3: Chaos Theory for you, or let me know what output logs are useful for me to send here.

**Comment by jlindgren90** [comment]
> if you press ToggleFullscreen once during any video, the black background disappears and the game window is moved to the left of the output.

It's expected that the black background disappears when leaving fullscreen, no? Or did I misunderstand?

Not sure why it would move to the left though.

> In addition, when you actually enter the game in Splinter Cell 3: Chaos Theory, the black background also disappears:

It looks like the game exited full screen. The bottom panel visible in the screenshot suggests that too.

I have a branch with some extra logging, I'll give a link in a bit. Appreciate the offer to share the game, but let's try some debug logging first.

**Comment by jlindgren90** [comment]
Extra logging commit: https://github.com/jlindgren90/labwc/commit/00b2b6087e7c5a36ea649de8dad11cb5a6948138

**Comment by danielfikko** [comment]
> It's expected that the black background disappears when leaving fullscreen, no? Or did I misunderstand?
> 
> Not sure why it would move to the left though.
> 

Yes, that's to be expected. I forgot to mention that when you return to full screen, the window moves to the left of the output, without the black background:

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/60cc9c36-a3d6-43c4-9fc0-73bab647a2b5" />

Furthermore, I mentioned earlier that Splinter Cell 3: Chaos Theory starts without a black background, which is still true. However, I implied that it was because of the introductory video, but that's not the case: the game has an option to start without the introductory video (`-nointro`) and continues to start without the black background.

Your guess about the game going out of full screen makes sense. Old games are complicated. Looking at the configuration file for Splinter Cell 3: Chaos Theory (`SplinterCell3.ini`), there are these options:

```
[WinDrv.WindowsClient]
StartupFullscreen=True

[D3DDrv.D3DRenderDevice]
UseFullscreen=False
```

Setting `UseFullscreen=True` does not solve the issue. I mean, that would just mask the issue and Splinter Cell 1 and 3 even support my output resolution (1920x1080) natively, but Splinter Cell 2 does not support it and suffers from the same issues.

Anyway, here are the output logs...

`WAYLAND_DEBUG=server labwc --debug`:
[labwc-output-log.txt](https://github.com/user-attachments/files/23811570/labwc-output-log.txt)

`DISPLAY= WAYLAND_DEBUG=client WINEDEBUG=+pid,+system,+tid,+timestamp,+vulkan,+waylanddrv,+win WINEPREFIX=~/.local/share/wine/wine wine ./splintercell3.exe` (perhaps @afrantzis can assist):
[splintercell3-output-log.txt](https://github.com/user-attachments/files/23811574/splintercell3-output-log.txt)

EDIT: I just tested Splinter Cell 3 on sway and the game starts with a black background. It doesn't suffer from the issue during videos, but it does suffer from the issue when entering the game: the black background disappears, probably because the game is going out of full screen. If it's a game issue or a `winewayland.drv` issue, I believe it can be ignored.

**Comment by jlindgren90** [comment]
Thanks for the logs. It's still a race with the configure timeout. This is the relevant part:

```
00:01:00.016 [DEBUG] [../src/action.c:1580] Handling action 19: ToggleFullscreen
00:01:00.016 [ERROR] [../src/view.c:1763] [Tom Clancy's Splinter Cell Chaos Theory] view_set_fullscreen(1)
...
00:01:00.116 [ERROR] [../src/xdg.c:323] client (splintercell3.exe) did not respond to configure request in 100 ms
00:01:00.116 [ERROR] [../src/view.c:644] [Tom Clancy's Splinter Cell Chaos Theory] moved to 0,0 1440x1080
```

I need to think about how to solve this.

**Comment by danielfikko** [comment]
@jlindgren90 By the way, I'm pretty sure I've been getting this error (`client did not respond to configure request in 100 ms`) for quite some time (even before your PR). I didn't know it was an issue.

Also, this reminds me of that MR for `winewayland.drv`:
https://gitlab.winehq.org/wine/wine/-/merge_requests/7525

That MR was created in response to an issue I reported to Wine, but at the time I tested it, the issue itself was not resolved. Right now, I'm going to compile Wine with that MR to test it. Do you think there's any relevance?

**Comment by danielfikko** [comment]
Well, no. That MR for `winewayland.drv` didn't solve any of the issues.

**Comment by jlindgren90** [comment]
> when you return to full screen, the window moves to the left of the output, without the black background

To clarify, this is the issue that's due to the configure timeout. I was able to reproduce it in StarCraft by reducing `CONFIGURE_TIMEOUT_MS` to 10. It should be fixed by https://github.com/jlindgren90/labwc/commit/266b5d2e040379c6e0f4e4eab189c288a2367335, please test. Extra debug output is in https://github.com/jlindgren90/labwc/commit/9d71fb6cfd88436fe157bcbffd5c0649bd85cf1a if needed again.

> I'm pretty sure I've been getting this error (client did not respond to configure request in 100 ms) for quite some time (even before your PR). I didn't know it was an issue.

The timeout itself isn't necessarily an issue; it can happen if the application is just busy for a bit. It's expected that it can cause some momentary visual glitches, but it shouldn't result in anything like the issue you saw. That was an oversight in my PR.

**Comment by danielfikko** [comment]
@jlindgren90 Happily, the issue of running `ToggleFullscreen` and the window moving to the left of the output and the black background disappearing has been resolved!

Now the issue is when you set the Splinter Cell 1 resolution to 1920x1080 (which is my output resolution). The introductory video appears normally, the window is centered and there is a black background, but the start menu is moved to the right of the output:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/d41a6a02-e4a8-4a56-8d95-2bb55e6ecee7" />

The same happens with the loading screen:
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/01cb9ad3-ae34-4d3e-bbc5-c256bb131ec6" />

In-game, the window is positioned correctly.

This also happens the first time you configure Splinter Cell 3 to use 1920x1080 resolution, but after restarting the game, this issue is no longer present. It is only persistent in Splinter Cell 1.

And one detail I just noticed: Splinter Cell 3 starts without the black background because it is actually starting outside of full screen mode, just like when you enter the game. When you exit the game and return to the start menu, the game also exits full screen mode. Apart from that, and the issue mentioned above, I don't see any other issues with the Splinter Cell franchise games.

output log, reproducing the issues:
[labwc-output-log.txt](https://github.com/user-attachments/files/23815475/labwc-output-log.txt)

**Comment by danielfikko** [comment]
Another issue: when you return to the game from Alt + Tab and the cursor is outside the game window and inside the black background area, the game no longer receives mouse input.

**Comment by jlindgren90** [comment]
> Now the issue is when you set the Splinter Cell 1 resolution to 1920x1080 (which is my output resolution). The introductory video appears normally, the window is centered and there is a black background, but the start menu is moved to the right of the output:

Right. It was centered (and black fill added) when it was 1440x1080, but then was not un-centered when it grew to 1920x1080. I expect that is a regression in my previous fix. Oops.

Try https://github.com/jlindgren90/labwc/commit/151b27b031bb746d72bd9dab6d626d0c387588ab.

```
00:00:07.993 [ERROR] [../src/xdg.c:259] [Tom Clancy's Splinter Cell] size changed 0x0 -> 1440x1080
00:00:07.993 [ERROR] [../src/xdg.c:155] [Tom Clancy's Splinter Cell] center fullscreen 1440x1080 in 1920x1080
00:00:07.993 [ERROR] [../src/xdg.c:285] [Tom Clancy's Splinter Cell] apply geometry 1440x1080
00:00:07.993 [ERROR] [../src/view.c:644] [Tom Clancy's Splinter Cell] moved to 240,0 1440x1080
00:00:07.993 [ERROR] [../src/view.c:583] [Tom Clancy's Splinter Cell] view_set_fullscreen_bg_enabled(1)
...
00:00:12.839 [ERROR] [../src/xdg.c:259] [Tom Clancy's Splinter Cell] size changed 1440x1080 -> 1920x1080
00:00:12.839 [ERROR] [../src/xdg.c:285] [Tom Clancy's Splinter Cell] apply geometry 1920x1080
00:00:12.839 [ERROR] [../src/view.c:644] [Tom Clancy's Splinter Cell] moved to 240,0 1920x1080
00:00:12.839 [ERROR] [../src/view.c:583] [Tom Clancy's Splinter Cell] view_set_fullscreen_bg_enabled(0)
```

> Another issue: when you return to the game from Alt + Tab and the cursor is outside the game window and inside the black background area, the game no longer receives mouse input.

Probably an issue with cursor confinement, which ought to be keeping the cursor within the game window. I've noticed similar behavior here. I think that deserves filing a separate issue, if there isn't already one.

**Comment by danielfikko** [comment]
@jlindgren90 Well, I tested all four of my old games, and happily, your PR is working as expected in all of them! (Actually, the issues mentioned with Splinter Cell 3 still remain, but we can ignore them, since the game supports 1920x1080 natively and some of the issues are also present in sway).

Thank you very much for your persistent work on this feature. I must say again, the games are a thousand times better to play centered and with a black background :D

|Your PR|0.9.2|
|-|-|
|<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/6306dc92-05ef-4994-ae02-b4fa51b38593" /> |<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/2817e3b4-4780-43e0-b028-d52c8638d849" />|

> Probably an issue with cursor confinement, which ought to be keeping the cursor within the game window. I've noticed similar behavior here. I think that deserves filing a separate issue, if there isn't already one.

Sure. Would you like me to open it?

**Comment by jlindgren90** [comment]
Yes please, open a new issue. I didn't see any existing ones except #475, which is very old and predates the original cursor constraints implementation in #586 - so probably not relevant.

**Comment by Consolatis** [comment]
Should be fixed in the master branch, thanks for reporting and testing!
