### ISSUE TITLE
Missing mouse grabbing feature?

### ISSUE THREAD

**Issue by vanfanel** [labwc/labwc#809]
Hi there!

I have noticed that, with the labwc compositor, some RetroArch cores have mouse problems.
For example, dosbox-core has pointer wrongly locked to a small area of the screen until the cursor is moved around beyond this small area:
https://github.com/realnc/dosbox-core/issues/48

This seems to be caused by the lack of mouse grabbing, which is a feature implemented (I guess) by the Wayland compositors.

So, would it be possible to have this feature implemented, please? Or maybe there's a problem with the current implementation?

Thanks!

**Comment by Consolatis** [comment]
"Mouse grabbing" in the wayland context is two things AFAIU:
- cursor confinement which restricts the cursor to a specific area of the surface
- cursor confinement which locks the cursor into a specific place

Related to the lock confinement, there is also a relative pointer motion protocol which (even though the actual cursor doesn't move) tells the wayland client about relative movements of the cursor and thus can be used by applications to render their own cursor. So I think the compositor side of the puzzle should be working, maybe RetroArch / dosbox-core (I don't really know how either of them work) just don't implement the "grab cursor" feature when it detects that its running under wayland?

**Comment by vanfanel** [comment]
@Consolatis I would like, at last, know where the problem really is: on the Wayland/labwc or on the RetroArch side. Thanks for trying to help me finding out! :)

What function should be used from RetroArch's side to grab the mouse, please? I can look on the RetroArch sources for that function, so I can find out if it's being used or not.

The idea of the missing compensation for scaling is also very plausible: the games in RetroArch are scaled from, let's say, 320x200, to 1920x10080.
Would the lack of scaling compensation cause cursor to be confined to a region and then moving it would finally "unlock" it?

**Comment by johanmalm** [comment]
Are you running the latest master branch. We very recently (<2 weeks) applied a patch on pointer constraints.

If running the latest doesn't solve this, could you try `sway` and/or `weston` before we start looking too deep.

**Comment by vanfanel** [comment]
> Are you running the latest master branch. We very recently (<2 weeks) applied a patch on pointer constraints.
> 
> If running the latest doesn't solve this, could you try `sway` and/or `weston` before we start looking too deep.

Y es, I'm running the latest GIT code: cursor confinement in fullscreen mode works perfectly in Scummvm since these changes you mention! scummvm runs on SDL2.

Sway and Weston have the exact same problem with the dosbox-core core in retroarch. I understand they implement all the grabbing functions?

**Comment by Consolatis** [comment]
> Sway and Weston have the exact same problem with the dosbox-core core in retroarch. I understand they implement all the grabbing functions?

I'd assume so, yes (but didn't actually verify).

> Would the lack of scaling compensation cause cursor to be confined to a region and then moving it beyond the initial limits would finally "unlock" it?

I don't think so, that sounds like some retroarch / dosbox issue.
I've just tested using an output scale of `2` for a nested output and the confinement seems to work correctly in that case as well.

> What function should be used from RetroArch's side to grab the mouse, please? 

Should be either `zwp_pointer_constraints_v1_confine_pointer` or `zwp_pointer_constraints_v1_lock_pointer`

**Comment by vanfanel** [comment]
@Consolatis Ah, thanks for taking a look :)
I am trying to implement mouse grab in RetroArch, exactly in `input_wl_grab_mouse()` where you pointed me to.

However, first problem is that never did any Wayland specific coding, so I am getting `undefined reference` when adding a call to `zwp_pointer_constraints_v1_confine_pointer` or `zwp_pointer_constraints_v1_lock_pointer`.

I did a grep search on `/usr/local/include` on my system (which runs latest stable WLRoots and the fantastic latest GIT Labwc on top of it with no problems at all), and had zero results, which is very puzzling.
Are these plain functions? Then I guess they should be on some system-installed header file under /usr... unless I am fundamentally wrong on something.

**Comment by vanfanel** [comment]
@Consolatis Ok, opened the issue in RetroArch: https://github.com/libretro/RetroArch/issues/15057

Now, let's see what they say about this...

**Comment by vanfanel** [comment]
@Consolatis The last problem was on RetroArch and is now fixed! 
https://github.com/libretro/RetroArch/pull/15103#pullrequestreview-1347622580

So this can be closed.

Labwc is now my daily driver! Thanks a lot! This compositor is incredible.

**Comment by Consolatis** [comment]
Nice work. Congratz on adding the feature and getting it merged :)
