### ISSUE TITLE
Is there a working workspace list for any of the suggested bars?

### ISSUE THREAD

**Issue by agoodfellow123** [labwc/labwc#881]
Hello, I haven't been using labwc in a while. The reason I stopped using was silly but it mattered to me a lot. At the time I used it, there wasn't support for any of the bars to show the workspace list. Since then, I noticed xfce4panel got wayland support. So I thought that might be it but I actually have little hope of that working.

Ever since that, I also have seen people who [forked waybar](https://github.com/r-clifford/Waybar-Hyprland) and make it work for their own environments. For example this one uses wlr/workspaces module instead of sway/workspaces module however I haven't tried it on labwc yet.

Would any of these work? I really want to return back to labwc but my perfectionism keeps me away.

**Comment by johanmalm** [comment]
I'm sure we'll do this one day, but I prefer not to make promises about when.

Ref:
- https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40
- https://github.com/labwc/labwc-scope#25-configuration---desktop

**Comment by Tamaranch** [comment]
> Since then, I noticed xfce4panel got wayland support. So I thought that might be it but I actually have little hope of that working.

We have implemented a pre-support for ext-workspace-unstable in [libxfce4windowing](https://gitlab.xfce.org/xfce/libxfce4windowing) and the workspace switcher of xfce4-panel uses it, but of course for the moment it is only virtual, since no compositor supports this protocol to my knowledge. (And there's probably still some work to do on our side anyway.)

**Comment by agoodfellow123** [comment]
Roger that. Thank you. Do you know an easy way to follow when ext-workspace-unstable will get implemented in libxfce4windowing? If not I'll just check every six months.

**Comment by Tamaranch** [comment]
It is already (pre)implemented in libxfce4windowing. The question is when this protocol will be accepted upstream (for that you can follow the merge request above), so that compositors, including Labwc, start using it.

**Comment by agoodfellow123** [comment]
Got it!

**Comment by raitonoberu** [comment]
Here is my solution. It's pretty basic, but it fits my needs and can be used with any bar.
![image](https://github.com/labwc/labwc/assets/64320078/dc6e9f99-4dd0-46a9-9e9b-b58cdfb54aeb)

The idea is to make a script that listens to a named pipe and prints a list of workspaces on every update. labwc writes to this pipe when switching workspaces.

The script itself:
<details>

```bash
#!/bin/bash

# <config>
NUMBER=5
SYMBOL_CURRENT=""
SYMBOL_OTHER=""
PIPE=/tmp/workspace
WRAP=true
# </config>

# format_line takes the current workspace number [1..N] and prints a string
# representing the list of workspaces (e.g. 4 -> "0 0 0 1 0")
format_line() {
    before=`yes $SYMBOL_OTHER 2>/dev/null | head -n $(($1 - 1))`
    after=`yes $SYMBOL_OTHER 2>/dev/null | head -n $(($NUMBER - $1))`
    echo $before $SYMBOL_CURRENT $after
}

# remove an existing pipe and make a new one
rm -f $PIPE
mkfifo $PIPE

# print initial state
current=1
format_line $current

while true
do
    if read input <$PIPE; then
        if [ $input == "right" ]; then input=$((current + 1)); fi
        if [ $input == "left" ]; then input=$((current - 1)); fi

        if (( $input < 1 )); then
            if [ "$WRAP" == false ]; then continue; fi
            input=$NUMBER
        fi
        if (( $input > $NUMBER )); then
            if [ "$WRAP" == false ]; then continue; fi
            input=1
        fi
        if (( $input == $current )); then continue; fi

        format_line $input
        current=$input
    fi
done
```
</details>

Add actions to `rc.xml`:
<details>

```xml
<keyboard>
  <keybind key="W-1">
    <action name="GoToDesktop" to="1" />
    <action name="Execute"
      command="bash -c 'echo 1 > /tmp/workspace'" />
  </keybind>
  <keybind key="W-2">
    <action name="GoToDesktop" to="2" />
    <action name="Execute"
      command="bash -c 'echo 2 > /tmp/workspace'" />
  </keybind>
  <!-- and so on -->

  <keybind key="W-C-Left">
    <action name="GoToDesktop" to="left" />
    <action name="Execute"
      command="bash -c 'echo left > /tmp/workspace'" />
  </keybind>
  <keybind key="W-C-Right">
    <action name="GoToDesktop" to="right" />
    <action name="Execute"
      command="bash -c 'echo right > /tmp/workspace'" />
  </keybind>
</keyboard>
```
</details>

Use it like this (Waybar):
<details>

```json
"custom/workspaces": {
  "exec": "~/.config/waybar/scripts/workspaces"
}
```

You can also set up scrollable workspace switching using `wtype`:
```json
"custom/workspaces": {
  "exec": "~/.config/waybar/scripts/workspaces",
  "on-scroll-up": "wtype -M win -M ctrl -k right",
  "on-scroll-down": "wtype -M win -M ctrl -k left"
}
```
</details>

**Comment by stefonarch** [comment]
Nice, but it looks like it will work only if you switch workspaces by shortcut, I've apps tied to some workspace which are activated by click on the taskbar or by a link (browser and mail) and I use also mostly 3-finger swiping to switch. It would be nice if the OSD could "export" the target workspace but it would still not be enough.

**Comment by BGazotti** [comment]
It's been a while, but are there any plans to implement this in a consistent manner? Last I checked there were at least two unstable protocols that could be used (wlr-foreign-toplevel-management-unstable and ext-workspace-unstable) but the state of adoption seems to be rather lacking to put it lightly.

How are other compositor/bar combinations handling this (instead of falling back to sway-specific features)? I feel like we're missing an important feature here

**Comment by Consolatis** [comment]
`wlr-foreign-toplevel-management` is supported by labwc but doesn't support anything workspace related.

> How are other compositor/bar combinations handling this (instead of falling back to sway-specific features)? I feel like we're missing an important feature here but it doesn't help that there doesn't seem to be a standard way of getting it to work.

Some are likely rendering a panel within their own compositor thus they do already have the state and don't need a protocol for that. Others are likely using their own private wayland protocol or some other form of custom IPC.

Labwc generally will not support custom IPC nor private wayland protocols. However, in this case we may end up actually ignoring our own stance at some point and implement one of the unofficial variants because this is really getting ridiculous!
Similar thing for things like marking a window `Always-On-top` / `Visible-on-all-workspaces` via a taskbar.

Maybe we actually need a new `wayland-protocols` structure at some point that caters for these kind of (IMHO essential) protocols.

**Comment by droc12345** [comment]
There are some proposed changes in window switching behavior, 
with the changes, it would be possible to switch to any window on any workspace,
and I have some changes on top of that, that would show workspace of each window as well as 
state (full, max, min), but I think it will be after 7.1 before it's implemented.

see https://github.com/labwc/labwc/pull/1479#issuecomment-1924999781

**Comment by stefonarch** [comment]
> I have some changes on top of that, that would show workspace of each window as well as  state (full, max, min)

Can this be exported (including xwayland/xdg-shell information) to be used by some command or other tools like panels? Atm the only way to see if an app is running in xwayland mode is the switcher, a kind of list like `lswt` would be nice.

**Comment by droc12345** [comment]
No easy way export the data, as some of the data is internal with no easy way of sharing.
The foreign toplevel doesn't address things like workspace name/num.
That's why the window switcher has all the data itself, so that it can be easily seen,
with the new behavior, you can check for running or just swap over to the running app, no matter the ws.

**Comment by Consolatis** [comment]
> Atm the only way to see if an app is running in xwayland mode is the switcher, a kind of list like `lswt` would be nice.

Hacky workaround:
```bash
#!/bin/bash

x11=( $(wmctrl -l -x | awk '{print $3}' | sed 's/^[^.]*[.]//') )

wlrctl window list | while IFS=':' read -r app_id title; do
	backend="[xdg]"
	for WM_CLASS in "${x11[@]}"; do
		if test "$WM_CLASS" == "$app_id"; then
			backend="[x11]"
			break;
		fi
	done
	printf "%-15s\t%3s\t%s\n" "$app_id" "$backend" "$title"
done
```

**Comment by droc12345** [comment]
A socket that would only output certain data from certain commands would be ideal.
Though I do understand not wanting to mess with it both from a purist viewpoint as well as implementation,
because I'm not sure how straight forward it would be.

Another thought is something like window switcher, but the window wouldn't allow change, just display the data, though alt tab and then escape does almost that. A separate window could be made mostly transparent in perhaps an overlay fashion.

Just a couple of thoughts.

**Comment by vain** [comment]
What is the current state of this?

I use something similar to @raitonoberu’s solution for now, but all this is really clunky. This is one of the biggest showstoppers in my opinion.

Is there anything that outsiders like me can do, other than wait?

**Comment by dluciv** [comment]
> What is the current state of this?
> 
> I use something similar to @raitonoberu’s solution for now, but all this is really clunky. This is one of the biggest showstoppers in my opinion.

I agree completely. Actually labwc is likely the *only* convenient wlroots lightweight stacking compositor, but neither waybar nor sfwbar not other bars can deal with its workspaces.

**Comment by jp7677** [comment]
I've combined the keybinds with a script that writes the current workspace into file and lets waybar read it to show it as a number. It is not flawless but works most of the time. Note that config and script are fixed to 4 workspaces and I have tried to disable any workspace switching other than the keybinds. So no click on an icon in the taskbar.

rc.xml: 

```xml
    <desktops number="4" />

    <keybind key="C-A-Left">
        <action name="GoToDesktop" to="left" wrap="no" />
        <action name="Execute" command="~/.config/labwc/workspace.sh left" />
    </keybind>
    <keybind key="C-A-Right">
        <action name="GoToDesktop" to="right" wrap="no" />
        <action name="Execute" command="~/.config/labwc/workspace.sh right" />
    </keybind>
    <keybind key="S-A-Left">
        <action name="SendToDesktop" to="left" wrap="no" />
        <action name="Execute" command="~/.config/labwc/workspace.sh left" />
    </keybind>
    <keybind key="S-A-Right">
        <action name="SendToDesktop" to="right" wrap="no" />
        <action name="Execute" command="~/.config/labwc/workspace.sh right" />
    </keybind>
```

workspace.sh:

```bash
#!/bin/sh
read -r line < $HOME/.config/labwc/current-workspace

if [[ $1 = "right" ]]
then
    if [[ $line -lt 4 ]]
    then
        ((line++))
    fi
else
    if [[ $line -gt 1 ]]
    then
        ((line--))
    fi
fi

truncate -s 0 $HOME/.config/labwc/current-workspace
echo $line >> $HOME/.config/labwc/current-workspace
```

autostart:

```bash
<snip>
# Reset workspaces
echo 1 > $HOME/.config/labwc/current-workspace
```

waybar's config

```json
<snip>
    "modules-left": ["custom/user", "custom/workspace", "wlr/taskbar"],
<snip>
    "wlr/taskbar": {
        "icon-size": 24,
        "all-outputs": true,
        "on-click": ""
    },
    "custom/workspace": {
        "format": "{}",
        "exec": "tail -F $HOME/.config/labwc/current-workspace 2> /dev/null",
        "tooltip": false,
    },
<snip>
```

waybar's style.css

```css
<snip>
#custom-workspace {
    font-weight: bolder;
    background: #353535;
    margin: 7px 5px 7px 5px;
    min-width: 15px;
}
<snip>
```

**Comment by playwithworst** [comment]
Since https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40 has been merged, is there now a way to do this properly?

**Comment by johanmalm** [comment]
> Since https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40 has been merged, is there now a way to do this properly?

Close. See #2365

**Comment by Consolatis** [comment]
You can also use the cosmic-workspace protocol, it should already work fine with sfwbar and labwc (>= 0.8.1). Labwc will support both for some time and then deprecate the cosmic variant. Sfwbar supports both protocols in its latest master. For waybar there is a [PR](https://github.com/Alexays/Waybar/pull/3481) which adds support for the cosmic variant.

Note that this still does not allow to only show windows on the currently active workspace in the panel nor allow to move windows to another workspace via panel. For that, another integration protocol is required which will very likely also require the ext-foreign-toplevel suite of interfaces to be [accepted](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/196).

**Comment by jp7677** [comment]
See this PR for adding support for ext-workspace-v1 to Waybar: https://github.com/Alexays/Waybar/pull/4016
Not sure though if this fits as-is into Waybar, no feedback yet from maintainers there.

**Comment by Alanon202** [comment]
> See this PR for adding support for ext-workspace-v1 to Waybar: [Alexays/Waybar#4016](https://github.com/Alexays/Waybar/pull/4016) Not sure though if this fits as-is into Waybar, no feedback yet from maintainers there.

Just built Waybar from your fork and it works nicely on Arch for my (admittedly simple setup) 4-5 virtual desktops on a single laptop screen. I can finally stop using my hacky scripts for this basic functionality. Thank you!

Sadly there doesn’t look to be much interest or feedback in your merges over at Waybar. I’m curious, in case nothing happens with upstream, @jp7677 do you plan on keeping your fork updated?

**Comment by kcirick** [comment]
Hi, just tried your fork and it works great! 

Is there a trick to indicate “occupied” workspace (non-active workspaces with one or more clients)? Waybar wiki seems to have a css class for empty workspaces but it doesn’t really seem to do anything.

**Comment by jp7677** [comment]
> Hi, just tried your fork and it works great!
> 
> Is there a trick to indicate “occupied” workspace (non-active workspaces with one or more clients)? Waybar wiki seems to have a css class for empty workspaces but it doesn’t really seem to do anything.

It’s probably better to add your comment/question to the PR. That said, thanks and no, the protocol only knows about active, urgent, hidden or no state. See https://wayland.app/protocols/ext-workspace-v1#ext_workspace_handle_v1:enum:state

**Comment by jp7677** [comment]
> See this PR for adding support for ext-workspace-v1 to Waybar: [Alexays/Waybar#4016](https://github.com/Alexays/Waybar/pull/4016) Not sure though if this fits as-is into Waybar, no feedback yet from maintainers there.

This became part of https://github.com/Alexays/Waybar/releases/tag/0.14.0 ! Hurray ;)

**Comment by johanmalm** [comment]
Thanks @jp7677 
I've submitted https://github.com/labwc/labwc.github.io/pull/74 to mention this.

**Comment by tomicooler** [comment]
Thanks @jp7677 , it is already out on Arch. It works great.


The only thing I miss is to show the windows only from the current workspace on the wlr/taskbar.

https://github.com/Alexays/Waybar/issues/1997

**Comment by jp7677** [comment]
> The only thing I miss is to show the windows only from the current workspace on the wlr/taskbar.
> [Alexays/Waybar#1997](https://github.com/Alexays/Waybar/issues/1997)

I haven't seen much from the taskbar module, but what I know: The protocol behind the `wlr/taskbar` module (https://gitlab.freedesktop.org/wlroots/wlr-protocols/-/blob/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml) has no knowledge of the work spaces concept. So this is currently not possible when purely sticking to Wayland protocols like labwc is doing. There are attempts to fill this gap in https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests , but things move slowly there.
